version: "latest"
services:
  db:
    container_name: "biblioteca-postgres"
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=BibliotecaPDF
      - POSTGRES_PASSWORD=Senha123!
    networks:
      - "bibliotecaPDF"
  cache:
    container_name: biblioteca-cache
    image: redis:latest
    networks:
      - "bibliotecaPDF"
    ports:
      - "6379:6379"  
    restart: always
  # app:
  #   depends_on: 
  #     - db
  #   container_name: "bibliotecaAPI"
  #   build: ./dockerfile
  #   image: "./"
  #   ports:
  #     - 5090:5090
  #   networks:
  #     - "bibliotecaPDF"

networks:
  bibliotecaPDF:
    driver:  bridge
#volumes:
#  db_volume: