version: "latest"
services:
  db:
    container_name: "bibliotecaDB"
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=BibliotecaPDF
      - POSTGRES_PASSWORD=Senha123!
    networks:
      - "bibliotecaPDF"
    #volumes:
    #  - "./db_volume:/var/opt/mssql/data"
  
  # app:
  #   depends_on: 
  #     - db
  #   container_name: "bibliotecaAPI"
  #   build: ./dockerfile
  #   image: "./"
  #   ports:
  #     - 5090:5090
  #   networks:
  #     - "bibliotecaPDF"

networks:
  bibliotecaPDF:
    driver:  bridge
#volumes:
#  db_volume: