name: .NET AI Code Review

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  dotnet-ai-code-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}    
      
      - name: Build Docker image
        run: docker build -t ymaschietto/my-ai-review:latest .

      - name: Run code review
        run: |
          docker run --rm \
            -v $(pwd):/app \
            -e OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
            -e PR_NUMBER=${{ github.event.number }} \
            -e GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} \
            ymaschietto/my-ai-review:latest