name: .NET AI Code Review

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  dotnet-ai-code-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}    
      
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v41
  
      - name: Run AI Code Review in Docker
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker run --rm \
            -e OPENAI_API_KEY="$OPENAI_API_KEY" \
            -e PR_NUMBER="$PR_NUMBER" \
            -e GITHUB_TOKEN="$GITHUB_TOKEN" \
            -v $(pwd):/repo \
            -w /app \
            -a STDOUT \
            ymaschietto/my-ai-review:latest